CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3360=y
CONFIG_PMW3360_CPI=400
CONFIG_PMW3360_CPI_DIVIDOR=1
CONFIG_PMW3360_ORIENTATION_270=y
CONFIG_PMW3360_INVERT_X=y

# central-only features (WPM needs keycode events, not available on peripheral)
CONFIG_ZMK_WPM=y
CONFIG_ZMK_HID_INDICATORS=y
