CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3360=y
CONFIG_PMW3360_CPI=400
CONFIG_PMW3360_CPI_DIVIDOR=1
CONFIG_PMW3360_ORIENTATION_270=y
CONFIG_PMW3360_INVERT_X=y

# aggressive REST mode downshift for battery life
# RUN(~20mA) -> 100ms -> REST1(~5mA) -> 400ms -> REST2(~2mA) -> 3.2s -> REST3(~1mA)
CONFIG_PMW3360_RUN_DOWNSHIFT_TIME_MS=100
CONFIG_PMW3360_REST1_DOWNSHIFT_TIME_MS=320
CONFIG_PMW3360_REST2_DOWNSHIFT_TIME_MS=3200

# central-only features
CONFIG_ZMK_HID_INDICATORS=y
